export const SET_QUIZ_TYPE = "SET_QUIZ_TYPE";

export const ADD_RESULT_TYPE = "ADD_RESULT_TYPE";

export const EDIT_RESULT_TYPE = "EDIT_RESULT_TYPE";

export const CLEAR_RESULT_TYPE = "CLEAR_RESULT_TYPE";